#!/bin/sh

cat /dev/stdin > temp
./translate_solitaire temp > log
if [ -f soln ]; then
    cat soln
    rm -f soln temp log
else
    grep 'Completely explored state space -- no solution!' log > /dev/null
    if [ $? -eq 0 ]; then
        echo INCONSISTENT
    fi
    rm -f temp log
fi
