#!/bin/sh

DOWNWARD_SRC=fd/src/

# Paths to planner components
TRANSLATE="./translate/translate.py"
PREPROCESS="./preprocess/preprocess"
SEARCH="./search/downward-1"

python translate_solitaire.py $1 > problem.pddl

python $DOWNWARD_SRC/translate/translate.py peg-domain.pddl problem.pddl
$DOWNWARD_SRC/preprocess/preprocess < output.sas
$DOWNWARD_SRC/search/downward --heuristic "hff=ff()" --search "eager_greedy(hff, preferred=(hff))" --plan-file out < output

python translate_sol_solitaire.py out > soln

rm -f output sas_plan elapsed.time output.sas problem.pddl test.groups all.groups out plan_numbers_and_cost
