(define (domain hydraulic-leaking)
  (:requirements :typing :action-costs :adl)
  (:types node valve - object
          tank jet junction - node)
  (:predicates (open ?v - valve)
	       (leaking ?v - valve)
	       (pressurized ?n - node)
	       (full ?n - node)
               (link ?n1 ?n2 - node ?v - valve))
  (:functions (total-cost) - number)

  (:action switchon-nonleaking
   :parameters (?v - valve ?from ?to - node)
   :precondition (and (not (leaking ?v))
                      (link ?from ?to ?v)
                      (pressurized ?from)
                      )
   :effect       (and (open ?v)
                      (pressurized ?to)
                      (increase (total-cost) 1)
                      )
   )
  (:action switchon-leaking
   :parameters (?v - valve ?from ?to - node)
   :precondition (and (leaking ?v)
                      (link ?from ?to ?v)
                      (pressurized ?from)
                      )
   :effect       (and (open ?v)
                      (pressurized ?to)
                      (increase (total-cost) 1000)
                      )
   )
)
