(define (domain hydraulic-leaking)
  (:requirements :typing :action-costs :adl :derived-predicates)
  (:types node valve - object
          tank jet junction - node)
  (:predicates (open ?v - valve)
	       (leaking ?v - valve)
	       (pressurized ?n - node)
	       (full ?n - node)
               (link ?n1 ?n2 - node ?v - valve))
  (:functions (total-cost) - number)

  (:action switchon-nonleaking
   :parameters (?v - valve ?from ?to - node)
   :precondition (and (not (leaking ?v))
                      (link ?from ?to ?v)
                      (pressurized ?from)
                      )
   :effect       (and (open ?v)
                      (pressurized ?to)
                      (increase (total-cost) 1)
                      )
   )
  (:action switchon-leaking
   :parameters (?v - valve ?from ?to - node)
   :precondition (and (leaking ?v)
                      (link ?from ?to ?v)
                      (pressurized ?from)
                      )
   :effect       (and (open ?v)
                      (pressurized ?to)
                      (increase (total-cost) 1000)
                      )
   )
  (:derived (pressurized ?n - node)
        (or (full ?n)
             (exists (?n1 - node) (exists (?v - valve) (and (pressurized ?n1) (link ?n1 ?n ?v) (open ?v)))))
   )
)
