#!/bin/bash


DIRNAME=`dirname $0`
SOLVER=$DIRNAME/clingo
ENCODING=$DIRNAME/checker.asp
TMPFILE=`mktemp`

cat - > $TMPFILE

maxstep=`cat $TMPFILE $DIRNAME/maxstep.asp | $SOLVER 2>/dev/null | grep maxstep | tr '()' '= '`

cat $TMPFILE $ENCODING | $SOLVER -c $maxstep | grep -q "^Answer: "

if [ $? = 0 ]; then
    echo "OK";
else
    echo "FAIL";
fi

rm $TMPFILE

