#!/bin/sh

DOWNWARD_SRC=fd/src/

# Paths to planner components
TRANSLATE="./translate/translate.py"
PREPROCESS="./preprocess/preprocess"
SEARCH="./search/downward-1"

python translate_airport.py $1 > problem.pddl

python $DOWNWARD_SRC/translate/translate.py air-domain.pddl problem.pddl
$DOWNWARD_SRC/preprocess/preprocess < output.sas
$DOWNWARD_SRC/search/downward --heuristic "h=cg()" --search "eager_greedy(h, preferred=(h))" --plan-file out < output

python translate_sol_airport out > soln

rm -f output sas_plan elapsed.time output.sas test.groups all.groups out plan_numbers_and_cost problem.pddl
