#! /usr/bin/env python2.6
# -*- coding: utf-8 -*-

def convert_airport_solution(filename):
    text = open(filename).read().strip()
    if text:
        last_dest = ""
        step = 1
        for action in text.split("\n"):
            action = action.strip()
            action = action[1:-1]
            args = action.split()
            coordinates = args[1].split("-")
            if(args[0] == "refuel"):
                print "%s(%s,%s)." % (args[0],args[1],step)
            elif(args[0] == "drive"):
                print "%s(%s,%s,%s)." % (args[0],args[1],args[3][4:],step)
            elif(args[0] == "pick" or args[0] == "drop"):
                print "%s(%s,%s,%s)." % (args[0],args[2],args[1],step)
            step += 1
    
if __name__ == "__main__":
    import sys
    convert_airport_solution(sys.argv[1])
