#! /bin/bash

cd $(dirname "$0")

if [[ $(hostname) == "alfons" ]]; then
    FIG_DIR=~/papers/ICAPS09_HMax/figures
elif [[ $(hostname) == "nils" ]]; then
    FIG_DIR=~/repos/papers/ICAPS09_HMax/figures
else
    FIG_DIR=.
fi

echo Generating $FIG_DIR/detailed-results-table.tex...
./lmcut-parse-detailed-results.py > $FIG_DIR/detailed-results-table.tex
echo Generating $FIG_DIR/coverage-table.tex...
./lmcut-parse-coverage.py > $FIG_DIR/coverage-table.tex
echo Generating $FIG_DIR/accuracy-table.tex...
./lmcut-parse-h.py > $FIG_DIR/accuracy-table.tex
