#! /bin/bash

for x in issue7-r*/results/search/version-*/*; do
    DOMAIN=$(basename "$x")
    y=$(dirname "$x")
    VERSION=$(basename "$y")
    y=$(dirname "$y")
    y=$(dirname "$y")
    REV=$(dirname "$y")
    NUMSOLVED=$(ls "$x"/*/sas_plan | wc -l)
    printf '%-22s %-22s %-22s %3d\n' "$DOMAIN" "$VERSION" "$REV" "$NUMSOLVED"
done

