#! /bin/bash

TRUNK_REV=3842

function setup {
    echo setting up planner...
    svn checkout svn+ssh://downward/trunk@$TRUNK_REV issue7 || exit 1
    cd issue7/downward
    ./build_all || exit 1
    cd ../..
    echo setup done!
    echo
}

if [[ ! -e issue7 ]]; then
    setup
fi

which qsub > /dev/null || {
    echo qsub not found. ssh habakuk?
    exit 1
}

TRANSLATE_URL=svn+ssh://downward/branches/translate-andrew/downward/translate
TRANSLATE_ALT_URL=svn+ssh://downward/trunk/downward/translate

## SUITE_1 is run with LM-cut and with merge-and-shrink (using A*)
## SUITE_2 is run with FF and with h^cea (using greedy BFS and pref. ops)
# SUITE="gripper grid"
# SUITE_1="grid"
# SUITE_2="gripper grid"

SUITE="ALL openstacks-strips pathways-noneg trucks-strips"
SUITE_1="LMCUT_DOMAINS"
SUITE_2="ALL"

if [[ $# == 0 ]]; then
    ## If called without arguments, compare the following revisions:
    ## 3827 -- old trunk (before Andrew's patch)
    ## 3829 -- Andrew's patch (with bugfix from msg185 in issue7)
    ## 3840 -- final revision in the branch
    ## 4283 -- after disabling ADD_IMPLIED_PRECONDITIONS, see msg325 in issue7.
    REVS="3827 3829 3840 4283"
else
    REVS="$@"
fi

function test-revision {
    REV=$1
    REVDIR=issue7-r$REV
    mkdir $REVDIR || exit 1
    cd $REVDIR
    mkdir downward
    mkdir results
    ln -s ../issue7/benchmarks .
    cd downward
    ln -s ../../issue7/downward/preprocess .
    ln -s ../../issue7/downward/search .
    svn checkout $TRANSLATE_URL@$REV || svn checkout $TRANSLATE_ALT_URL@$REV
    cd ..
    svn checkout svn+ssh://downward/trunk/scripts@$TRUNK_REV
    cd scripts
    cp ../../support/create-gkigrid-experiment-{1,2}.py .
    PRE_SCRIPT=r$REV-preprocess.q
    EXP1_SCRIPT=r$REV-experiment1.q
    EXP2_SCRIPT=r$REV-experiment2.q
    ./create-gkigrid-preprocess.py $PRE_SCRIPT $SUITE
    ./create-gkigrid-experiment-1.py $EXP1_SCRIPT $SUITE_1
    ./create-gkigrid-experiment-2.py $EXP2_SCRIPT $SUITE_2
    qsub $PRE_SCRIPT
    qsub -p -1 -hold_jid $PRE_SCRIPT $EXP1_SCRIPT
    qsub -p -1 -hold_jid $PRE_SCRIPT $EXP2_SCRIPT
    cd ..
    cd ..
}

for rev in $REVS; do
    test-revision $rev
done
