#! /bin/bash

BASEDIR=../../..
LOGDIR=$BASEDIR/results/jair-2008/strategies/

./cleanup-summary/extract -f $LOGDIR/SUMMARY-11.log -n 1 > $LOGDIR/CLEAN-11

./cleanup-summary/extract -f $LOGDIR/SUMMARY-21.log -n 11 > $LOGDIR/CLEAN-21

./cleanup-summary/extract -f $LOGDIR/SUMMARY-31.log -n 1 > $LOGDIR/CLEAN-31

./cleanup-summary/extract -f $LOGDIR/SUMMARY-41.log -n 11 > $LOGDIR/CLEAN-41

./cleanup-summary/extract -f $LOGDIR/SUMMARY-12.log -n 1 > $LOGDIR/CLEAN-12

./cleanup-summary/extract -f $LOGDIR/SUMMARY-13.log -n 1 > $LOGDIR/CLEAN-13

./cleanup-summary/extract -f $LOGDIR/SUMMARY-14.log -n 11 > $LOGDIR/CLEAN-14

