#! /bin/bash

BASEDIR=../../..

LOGDIR=$BASEDIR/results/jair-2008/strategies/11
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/strategies/21
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/strategies/31
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/strategies/41
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/strategies/12
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/strategies/13
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/strategies/14
rm -rf $LOGDIR
mkdir -p $LOGDIR



