#! /bin/bash

BASEDIR=../../..

LOGDIR=$BASEDIR/results/jair-2008/strategies/11
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-11.log

LOGDIR=$BASEDIR/results/jair-2008/strategies/21
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-21.log

LOGDIR=$BASEDIR/results/jair-2008/strategies/31
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-31.log

LOGDIR=$BASEDIR/results/jair-2008/strategies/41
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-41.log

LOGDIR=$BASEDIR/results/jair-2008/strategies/12
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-12.log

LOGDIR=$BASEDIR/results/jair-2008/strategies/13
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-13.log

LOGDIR=$BASEDIR/results/jair-2008/strategies/14
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-14.log


