#!/bin/sh
#
#PBS -q bfg
#PBS -o driver.log
#PBS -e driver.err
#PBS -N %(jobname)s

pwd
date
hostname
echo
ulimit -a
echo
echo Setting up inputs...
ln -s ../../inputs/%(problem)s/* .
echo
echo CPU info:
cat /proc/cpuinfo
echo
echo meminfo:
cat /proc/meminfo
echo
echo Starting planner...
ulimit -t %(timeout)d
ulimit -v %(memory_kb)d
../../resources/release-search %(config)s < output > search.log 2> search.err
echo exit code: $?
times
date
echo Done.
