#! /bin/bash

BASEDIR=../../..

LOGDIR=$BASEDIR/results/jair-2008/competitive/11
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/competitive/13
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/competitive/hmax
rm -rf $LOGDIR
mkdir -p $LOGDIR

LOGDIR=$BASEDIR/results/jair-2008/competitive/blind
rm -rf $LOGDIR
mkdir -p $LOGDIR




