#! /bin/bash
ulimit -t 1800
ulimit -v 3145728

PIPESNOTANK="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50"
PIPESTANK="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50"
SATELLITE="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36"
LOG00="4-0 4-1 5-0 5-1 6-0 6-1 7-0 7-1 8-0 8-1 9-0 9-1 10-0 10-1 11-0 11-1 12-0 12-1 13-0 13-1 14-0 14-1 15-0 15-1"
PSR="29 36 40 48 49"
TPP="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30"

BASEDIR=../../../..
SEARCH=$BASEDIR/downward/search/search
INPUTS=$BASEDIR/results/preprocess
LOGDIR=$BASEDIR/results/jair-2008/competitive/$1

for task in $PIPESNOTANK; do
    r=$2
    while [ $r -le $3 ]; do
	$SEARCH a 2500 A3 S$1 R$r < $INPUTS/pipesworld-notankage/p$task-*.pre \
	    | tee $LOGDIR/PIPESNOTANK-$task-${r}.log
	r=$[$r+1];
    done
done

for task in $PIPESTANK; do
    r=$2
    while [ $r -le $3 ]; do
	$SEARCH a 1000 A3 S$1 R$r < $INPUTS/pipesworld-tankage/p$task-*.pre \
	    | tee $LOGDIR/PIPESTANK-$task-${r}.log
	r=$[$r+1];
    done
done

for task in $SATELLITE; do
    r=$2
    while [ $r -le $3 ]; do
	$SEARCH a 10000 A3 S$1 R$r < $INPUTS/satellite/p$task-*.pre \
	    | tee $LOGDIR/SATELLITE-$task-${r}.log
	r=$[$r+1];
    done
done

for task in $LOG00; do
    r=$2
    while [ $r -le $3 ]; do
	$SEARCH a 200000 A3 S$1 R$r < $INPUTS/logistics00/probLOGISTICS-$task.pre \
	    | tee $LOGDIR/LOG00-$task-${r}.log
	r=$[$r+1];
    done
done

for task in $PSR; do
    r=$2
    while [ $r -le $3 ]; do
	$SEARCH a 200000 A3 S$1 R$r < $INPUTS/psr-small/p$task-*.pre \
	    | tee $LOGDIR/PSR-$task-${r}.log
	r=$[$r+1];
    done
done

for task in $TPP; do
    r=$2
    while [ $r -le $3 ]; do
	$SEARCH a 50000 A3 S$1 R$r < $INPUTS/tpp/p$task.pre \
	    | tee $LOGDIR/TPP-$task-${r}.log
	r=$[$r+1];
    done
done
