#! /bin/bash

BASEDIR=../../..

LOGDIR=$BASEDIR/results/jair-2008/competitive/11
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-11.log

LOGDIR=$BASEDIR/results/jair-2008/competitive/13
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-13.log

LOGDIR=$BASEDIR/results/jair-2008/competitive/hmax
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-hmax.log

LOGDIR=$BASEDIR/results/jair-2008/competitive/blind
../summarize-log.py $LOGDIR/*.log > $LOGDIR/../SUMMARY-blind.log



