#!/bin/sh
# $1 - ASP encoding of HANOI problem 

DOWNWARD_SRC=../../../src

rm -f nocomment pddl output.sas output sas_plan soln temp_file

cat $1 > temp_file

bound=`grep steps temp_file | gawk 'BEGIN {FS="(";} {print $2 + 1;}'`

gawk '{if (substr($1,1,1) != "%") print $0l}' temp_file > nocomment
python translate_hanoi.py nocomment > pddl

$DOWNWARD_SRC/translate/translate.py hanoi.pddl pddl
$DOWNWARD_SRC/preprocess/preprocess < output.sas
$DOWNWARD_SRC/search/downward --search "astar(selmax(lmcut(),hmax(),alpha=4,training_set=10),bound=$bound,pathmax=true)" < output

if [ -f sas_plan ]; then
    gawk '{disc = substr($2,2); to = substr($4,2) + 0; printf "put(" NR-1 "," to "," disc "). ";} END {print "";}' sas_plan > soln
fi

