#! /bin/sh

DOWNWARD_SRC=../../../src

python2.6 ./translate_hydraulic_planning.py /dev/stdin > problem.pddl
$DOWNWARD_SRC/translate/translate.py domain.pddl problem.pddl > translate.log
$DOWNWARD_SRC/preprocess/preprocess < output.sas > preprocess.log
$DOWNWARD_SRC/search/downward --search "astar(lmcount(lm_merged(lm_rhw(),lm_hm(m=1)),admissible=true),mpd=true)" < output > search.log

./create_asp_output.py search.log sas_plan

rm -f problem.pddl test.groups all.groups elapsed.time output.sas output plan_numbers_and_cost downward.tmp.* sas_plan