(define (domain sokoban-sequential)
  (:requirements :typing :action-costs)
  (:types thing location - object
          player stone - thing)
  (:predicates (clear ?l - location)
	       (at ?t - thing ?l - location)
	       (at-goal ?s - stone)
	       (up-last)
	       (down-last)
	       (left-last)
	       (right-last)
	       (up ?l1 - location ?l2 - location)
	       (down ?l1 - location ?l2 - location)
	       (left ?l1 - location ?l2 - location)
	       (right ?l1 - location ?l2 - location)
	       (IS-GOAL ?l - location)
	       (IS-NONGOAL ?l - location))
  (:functions (total-cost) - number)

  (:action move-up
   :parameters (?p - player ?from ?to - location)
   :precondition (and (at ?p ?from)
                      (clear ?to)
                      (up ?from ?to)
                      )
   :effect       (and (not (at ?p ?from))
                      (not (clear ?to))
                      (at ?p ?to)
                      (clear ?from)
                      (not (up-last))
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action move-down
   :parameters (?p - player ?from ?to - location)
   :precondition (and (at ?p ?from)
                      (clear ?to)
                      (down ?from ?to)
                      )
   :effect       (and (not (at ?p ?from))
                      (not (clear ?to))
                      (at ?p ?to)
                      (clear ?from)
                      (not (up-last))
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action move-left
   :parameters (?p - player ?from ?to - location)
   :precondition (and (at ?p ?from)
                      (clear ?to)
                      (left ?from ?to)
                      )
   :effect       (and (not (at ?p ?from))
                      (not (clear ?to))
                      (at ?p ?to)
                      (clear ?from)
                      (not (up-last))
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action move-right
   :parameters (?p - player ?from ?to - location)
   :precondition (and (at ?p ?from)
                      (clear ?to)
                      (right ?from ?to)
                      )
   :effect       (and (not (at ?p ?from))
                      (not (clear ?to))
                      (at ?p ?to)
                      (clear ?from)
                      (not (up-last))
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action push-up-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (up ?ppos ?from)
                      (up ?from ?to)
                      (IS-NONGOAL ?to)
                      (not (up-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      (increase (total-cost) 1)
                      (up-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )
   
  (:action push-up-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (up ?ppos ?from)
                      (up ?from ?to)
                      (IS-GOAL ?to)
                      (not (up-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      (increase (total-cost) 1)
                      (up-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action chain-push-up-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (up ?ppos ?from)
                      (up ?from ?to)
                      (IS-NONGOAL ?to)
                      (up-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      )
   )

  (:action chain-push-up-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (up ?ppos ?from)
                      (up ?from ?to)
                      (IS-GOAL ?to)
                      (up-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      )
   )

  (:action push-down-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (down ?ppos ?from)
                      (down ?from ?to)
                      (IS-NONGOAL ?to)
                      (not (down-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      (increase (total-cost) 1)
                      (down-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )
   
  (:action push-down-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (down ?ppos ?from)
                      (down ?from ?to)
                      (IS-GOAL ?to)
                      (not (down-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      (increase (total-cost) 1)
                      (down-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action chain-push-down-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (down ?ppos ?from)
                      (down ?from ?to)
                      (IS-NONGOAL ?to)
                      (down-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      )
   )

  (:action chain-push-down-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (down ?ppos ?from)
                      (down ?from ?to)
                      (IS-GOAL ?to)
                      (down-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      )
   )

  (:action push-left-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (left ?ppos ?from)
                      (left ?from ?to)
                      (IS-NONGOAL ?to)
                      (not (left-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      (increase (total-cost) 1)
                      (left-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )
   
  (:action push-left-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (left ?ppos ?from)
                      (left ?from ?to)
                      (IS-GOAL ?to)
                      (not (left-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      (increase (total-cost) 1)
                      (left-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action chain-push-left-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (left ?ppos ?from)
                      (left ?from ?to)
                      (IS-NONGOAL ?to)
                      (left-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      )
   )

  (:action chain-push-left-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (left ?ppos ?from)
                      (left ?from ?to)
                      (IS-GOAL ?to)
                      (left-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      )
   )

  (:action push-right-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (right ?ppos ?from)
                      (right ?from ?to)
                      (IS-NONGOAL ?to)
                      (not (right-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      (increase (total-cost) 1)
                      (right-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )
   
  (:action push-right-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (right ?ppos ?from)
                      (right ?from ?to)
                      (IS-GOAL ?to)
                      (not (right-last))
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      (increase (total-cost) 1)
                      (right-last)
                      (not (down-last))
                      (not (left-last))
                      (not (right-last))
                      )
   )

  (:action chain-push-right-nongoal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (right ?ppos ?from)
                      (right ?from ?to)
                      (IS-NONGOAL ?to)
                      (right-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (not (at-goal ?s))
                      )
   )

  (:action chain-push-right-goal
   :parameters (?p - player ?s - stone
                ?ppos ?from ?to - location)
   :precondition (and (at ?p ?ppos)
                      (at ?s ?from)
                      (clear ?to)
                      (right ?ppos ?from)
                      (right ?from ?to)
                      (IS-GOAL ?to)
                      (right-last)
                      )
   :effect       (and (not (at ?p ?ppos))
                      (not (at ?s ?from))
                      (not (clear ?to))
                      (at ?p ?from)
                      (at ?s ?to)
                      (clear ?ppos)
                      (at-goal ?s)
                      )
   )
)
