#!/bin/bash
# Use this script to turn a run into the baseline
# $1 - directory to run on


# change from WORK to BASELINE in properties files

mv $1/exp-eval/properties $1/exp-eval/properties.old
sed -e 's/WORK/BASELINE/g' $1/exp-eval/properties.old > $1/exp-eval/properties
rm $1/exp-eval/data_dump

mv $1 `dirname $1`/baseline