#!/bin/bash
# $1 - name
# $2 - configs file
# $3 - suite file

RESULTS_BASE_DIR=~/results/$1
RESULTS_DIR=$RESULTS_BASE_DIR/`hg id -i`
BASELINE_DIR=$RESULTS_BASE_DIR/baseline

mkdir $RESULTS_DIR || exit

echo Creating Preprocessing Experiment
./downward_experiments.py --path exp-p -l WARNING -s `cat $3` --preprocess local

echo Running Preprocessing Experiment
exp-p/run

echo Fetching Preprocessing Results
./downward-resultfetcher.py exp-p -l WARNING 

echo Creating Experiment
./downward_experiments.py --path exp -l WARNING -c `cat $2` -s `cat $3` local

echo Running Experiment
exp/run

echo Extracting Results
./downward-resultfetcher.py exp -l WARNING 

echo Storing Results
cp -r exp-eval $RESULTS_DIR/exp-eval

echo Fetching Baseline Results
cat $BASELINE_DIR/exp-eval/properties >> exp-eval/properties

rm -f test.exp.output

echo Comparing Results to Baseline
for c in `sed -e 's/,/ /g' $2`; do
    echo Comparing Configuration $c;
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a expanded -c BASELINE-$c,WORK-$c >> test.exp.output; 
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a initial_h_value -c BASELINE-$c,WORK-$c >> test.exp.output; 
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a plan_length -c BASELINE-$c,WORK-$c >> test.exp.output;        
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a search_time -c BASELINE-$c,WORK-$c >> test.exp.output;
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a total_time -c BASELINE-$c,WORK-$c >> test.exp.output;
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a translator_vars -c BASELINE-$c,WORK-$c >> test.exp.output;
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a preprocessor_vars -c BASELINE-$c,WORK-$c >> test.exp.output;
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a translator_ops -c BASELINE-$c,WORK-$c >> test.exp.output;
    ./downward-reports.py -l WARNING exp-eval -r rel --change 5 --res problem -a preprocessor_ops -c BASELINE-$c,WORK-$c >> test.exp.output;       
done

rm -fr exp-eval
rm -fr exp
rm -fr exp-p

if [ -s test.exp.output ]; then
    cat test.exp.output
    exit 2    
else
    echo No Significant Differences;
fi    