#! /bin/bash

set -e

# NOTE: This only works with the IPC-2008 naming conventions.
# NOTE: This requires that "validate" is in the PATH and refers to
#       the VAL wrapper script to support action costs.

pushd . > /dev/null
cd "$(dirname "$0")"
BASEDIR="$PWD"
popd > /dev/null

for DIR in "$@"; do
    for PLAN in $(find "$DIR" -name sas_plan\*); do
        pushd . > /dev/null
        cd "$(dirname "$PLAN")"

        DOMAIN=$(grep '^domain =' properties | \
            sed -e "s/.*'\(.*\)'/\1/")
        PROBLEM=$(grep '^problem =' properties | \
            sed -e "s/.*'\(.*\)'/\1/")
        DOMAIN_DIR="$BASEDIR/../benchmarks/$DOMAIN"
        DOMAIN_FILE="$DOMAIN_DIR/${PROBLEM/.pddl/-domain.pddl}"
        PROBLEM_FILE="$DOMAIN_DIR/$PROBLEM"
        echo Run VAL on "$DOMAIN_FILE" "$PROBLEM_FILE" "$PLAN"...
        validate "$DOMAIN_FILE" "$PROBLEM_FILE" "$(basename "$PLAN")"
        echo
        popd > /dev/null
    done
done
