#!/bin/sh
# $1 - name
# $2 - configs
# $3 - suite

echo Creating Experiment
python downward-experiments.py $1 -c $2 -s $3

echo Running Experiment
$1/run

echo Fetching Results 
python downward-resultfetcher.py $1

echo Printing Results
for config in $1-eval/*; do 
    for domain in $config/*; do 
        for problem in $domain/*; do 
            python print_results.py $problem/properties 
        done;   
    done; 
done

echo Cleaning Up
rm -fr $1 $1-eval