#! /bin/bash

./do_preprocessing airport
./do_preprocessing assembly
./do_preprocessing blocks
./do_preprocessing depot
./do_preprocessing driverlog
./do_preprocessing freecell
./do_preprocessing grid
./do_preprocessing gripper
./do_preprocessing logistics00
./do_preprocessing logistics98
./do_preprocessing miconic
./do_preprocessing miconic-fulladl
./do_preprocessing miconic-simpleadl
./do_preprocessing movie
./do_preprocessing mprime
./do_preprocessing mystery
./do_preprocessing optical-telegraphs
./do_preprocessing philosophers
./do_preprocessing pipesworld-notankage
./do_preprocessing pipesworld-tankage
./do_preprocessing psr-middle
./do_preprocessing psr-small
./do_preprocessing rovers
./do_preprocessing schedule
./do_preprocessing zenotravel

## Moved to the end because some of these are BIG.
./do_preprocessing satellite
./do_preprocessing psr-large
