#!/bin/sh
# passes all arguments

make clean
make release HIGH_COST_ACTIONS=1 $*
mv -f release-search release-search_hca

make clean
make release STATE_VAR_SHORT=1 $*
mv -f release-search release-search_svs

make clean
make release STATE_VAR_SHORT=1 HIGH_COST_ACTIONS=1 $*
mv -f release-search release-search_svs_hca

make clean
make release $*

