#!/bin/sh

DOWNWARD_SRC=fd/src/

# Paths to planner components
TRANSLATE="./translate/translate.py"
PREPROCESS="./preprocess/preprocess"
SEARCH="./search/downward-1"

cat $1 > temp_trans

python translate_sokoban.py temp_trans > problem.pddl

BOUND=$(cat temp_trans | tr ' ' '\n' | grep "step" | tail -1 | awk '{print substr($1,6,length($1)-7)}')

#let "BOUND += 1"

rm -f temp_trans

python $DOWNWARD_SRC/translate/translate.py sokoban-domain.pddl problem.pddl
$DOWNWARD_SRC/preprocess/preprocess < output.sas
$DOWNWARD_SRC/search/downward --search "astar(lmcut(), bound=$BOUND)" --plan-file out < output

if [ -f out ]; then
    python translate_sol_sokoban.py out > soln
fi

rm -f output sas_plan elapsed.time output.sas problem.pddl test.groups all.groups out plan_numbers_and_cost
