#! /bin/bash

set -e

BASEDIR="$(dirname "$0")"

function die {
    echo "$@" 1>&2
    exit 1
}

function usage {
    die "usage: $(basename "$0") [DOMAIN_FILE] PROBLEM_FILE SEARCH_OPTION ..."
}

# Paths to planner components
TRANSLATE="$BASEDIR/translate/translate.py"
PREPROCESS="$BASEDIR/preprocess/preprocess"
SEARCH="$BASEDIR/search/downward"

# Settings
INV_TIME_LIMIT="300"

# Check for citation request
if [ "--citation" = "$1" ]; then
  echo "
@inproceedings{muise12icapsfond,
  author = {Christian Muise and Sheila A McIlraith and J Christopher Beck},
  title = {Improved Non-deterministic Planning by Exploiting State Relevance},
  booktitle = {The 22nd International Conference on Automated Planning and Scheduling (ICAPS)},
  year = {2012},
  subdiscipline = {Artificial Intelligence},
  type = {Conference Proceedings}
}

@inproceedings{muise-aaai-14,
  title={Computing Contingent Plans via Fully Observable Non-Deterministic Planning},
  author={Muise, Christian and Belle, Vaishak and McIlraith, Sheila A.},
  booktitle={The 28th AAAI Conference on Artificial Intelligence},
  year={2014},
  url={http://www.haz.ca/papers/muise-aaai-14.pdf}
}

@inproceedings{muise-icaps-14,
  title={Non-Deterministic Planning With Conditional Effects},
  author={Muise, Christian and McIlraith, Sheila A. and Belle, Vaishak},
  booktitle={The 24th International Conference on Automated Planning and Scheduling},
  year={2014},
  url={http://www.haz.ca/papers/muise-icaps-14.pdf}
}
"
  exit 1
fi

# Need to explicitly ask for GNU time (from MacPorts) on Mac OS X.
if [[ "$(uname)" == "Darwin" ]]; then
    TIME="gtime"
    if ! which $TIME >/dev/null; then
        die "$TIME must be installed on Mac OSX (from MacPorts, perhaps) for this to work"
    fi
else
    TIME="command time"
fi

TIME="$TIME --output=elapsed.time --format=%S\n%U\n"

IPC="ipc"
if [[ "$1" == "debug" ]]; then
    IPC="debug $IPC"
    shift
fi

run_planner() {
    echo "1. Running translator"
    $TIME "$TRANSLATE" "$INV_TIME_LIMIT" "$1" "$2" || exit 1
    echo "2. Running preprocessor"
    $TIME --append "$PREPROCESS" < output.sas || exit 1
    echo "3. Running search"
    shift
    shift
    PROB="$1"
    shift
    echo "$SEARCH" "$IPC" policy-repair-probabilistic --plan-file "$PROB" "$@" < output
    "$SEARCH" $IPC policy-repair-probabilistic --plan-file "$PROB" "$@" < output
}

check_input_files() {
    if [ ! -e "$1" ]; then
	echo "Domain file \"$1\" does not exist."
	exit 1
    fi
    if [ ! -e "$2" ]; then
	echo "Problem file \"$2\" does not exist."
	exit 1
    fi
}

# Make sure we have at least 2 command line arguments
if [[ "$#" -lt 2 ]]; then
    usage
fi

DOMAIN="$1"
shift
PROB="$1"
shift

check_input_files "$DOMAIN" "$PROB"

# Command line arguments seem to be fine, run planner
run_planner "$DOMAIN" "$PROB" "$RESULT" "$@"


