#! /bin/bash

# Skip over all initial arguments that don't end with *.pddl.
# This is, of course, a HACK, like this whole script.
SWITCHES=
while [[ "$1" == "${1%.pddl}" ]]; do
    SWITCHES="$SWITCHES $1"
    shift
done

DOMAIN=$(cat "$1" | sed -e 's/:action-costs/:fluents/' \
                  | sed -e 's/:goal-utilities/:preferences/' \
                  | sed -e 's/:numeric-fluents/:fluents/' \
                  | sed -e 's/-\s\s*number//')
## It looks like the following line might actually be sufficient
## as of most recent VAL:
## DOMAIN=$(cat "$1" | sed -e 's/-\s\s*number//')
shift

PROBLEM=$(cat "$1")
shift

VALIDATE_ORIG="$(dirname "$0")/validate-orig"
"$VALIDATE_ORIG" $SWITCHES <(echo "$DOMAIN") <(echo "$PROBLEM") "$@"
EXITCODE=$?
exit $EXITCODE
