#! /bin/bash

OLDDIR=`pwd`
cd ..
./do_preprocessing pipesworld-notankage
./do_preprocessing pipesworld-tankage
./do_preprocessing satellite
./do_preprocessing logistics00
./do_preprocessing psr-small
./do_preprocessing tpp
cd $OLDDIR

./run-lfpa
./run-blind
./run-hmax

