#! /bin/bash
ulimit -t 1800
ulimit -v 1572864

PIPESNOTANK="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 17 21 23 24"
PIPESTANK="01 02 03 04 05 06 07 08 11 13 15 21 31"
SATELLITE="01 02 03 04 05 06"
LOG00="4-0 4-1 5-0 5-1 6-0 6-1 7-0 7-1 8-0 8-1 9-0 9-1 10-0 10-1 11-0 11-1 12-0 12-1"
PSR="29 36 40 48 49"
TPP="01 02 03 04 05 06 07"

BASEDIR=../..
SEARCH=$BASEDIR/downward/search/search
INPUTS=$BASEDIR/results/preprocess
LOGDIR=$BASEDIR/results/icaps-2007/lfpa
mkdir -p $LOGDIR

for task in $PIPESNOTANK; do
    $SEARCH a 2500 D0A1 < $INPUTS/pipesworld-notankage/p$task-*.pre \
       | tee $LOGDIR/PIPESNOTANK-$task.log
done

for task in $PIPESTANK; do
    $SEARCH a 1000 D0A1 < $INPUTS/pipesworld-tankage/p$task-*.pre \
       | tee $LOGDIR/PIPESTANK-$task.log
done

for task in $SATELLITE; do
    $SEARCH a 10000 D0A3 < $INPUTS/satellite/p$task-*.pre \
       | tee $LOGDIR/SATELLITE-$task.log
done

for task in $LOG00; do
    $SEARCH a 200000 D0A1 < $INPUTS/logistics00/probLOGISTICS-$task.pre \
       | tee $LOGDIR/LOG00-$task.log
done

for task in $PSR; do
    $SEARCH a 200000 D0A1 < $INPUTS/psr-small/p$task-*.pre \
       | tee $LOGDIR/PSR-$task.log
done

for task in $TPP; do
    $SEARCH a 50000 D0A3 < $INPUTS/tpp/p$task.pre \
       | tee $LOGDIR/TPP-$task.log
done

./summarize-log.py $LOGDIR/*.log > $LOGDIR/../LFPA-SUMMARY.log
