#!/bin/sh

./translate_knight /dev/stdin > log
if [ -f soln ]; then
    cat soln
else
    grep 'Completely explored state space -- no solution!' log > /dev/null
    if [ $? -eq 0 ]; then
        echo INCONSISTENT
    fi
fi
