#!/bin/sh
# $1 - ASP encoding of HANOI problem 

DOWNWARD_SRC=../../../src

rm -f nocomment sas sas.fixed output soln sas_plan

gawk '{if (substr($1,1,1) != "%") print $0l}' $1 > nocomment
python translate_knight.py nocomment > sas

num_ops=`grep -c begin_operator sas`
gawk --assign=num_ops=$num_ops '{if ($0 == "NUM_OPS") print num_ops; else print $0;}' sas > sas.fixed


$DOWNWARD_SRC/preprocess/preprocess < sas.fixed
$DOWNWARD_SRC/search/downward --heuristic "h1=ff()" --heuristic "h2=goalcount()" --search "eager_greedy(h1,h2,preferred=(h1))" < output

gawk '{if ($1 == "(move") printf "move(" $2+1 "," $3+1 "," $4+1 "," $5 +1 ").";} END {print "";}' sas_plan > soln
